## Our testing here is rather complex, because we aren't slackers.
task:
    # Basic metadata:
    name: lang/mono 11.3
    # The build machine:
    freebsd_instance:
        image_family: freebsd-11-3
    # Instructions:
    pkg_preload_script: ci/pkg_preload
    port_setup_script: ci/ports_setup
    port_test_script: ci/port_test lang/mono5.20
task:
    # Basic metadata:
    name: lang/mono 12.1
    # The build machine:
    freebsd_instance:
        image_family: freebsd-12-1
    # Instructions:
    pkg_preload_script: ci/pkg_preload
    port_setup_script: ci/ports_setup
    port_test_script: ci/port_test lang/mono5.20
task:
    # Basic metadata:
    name: lang/mono HEAD
    # The build machine:
    freebsd_instance:
        image_family: freebsd-13-0-snap
    # Instructions:
    pkg_preload_script: ci/pkg_preload
    port_setup_script: ci/ports_setup
    port_test_script: ci/port_test lang/mono5.20


