#!/bin/sh
## Perform package preloading.
env ASSUME_ALWAYS_YES=YES pkg bootstrap
case $(/bin/freebsd-version -u) in
	1[12]*)
		pkg install -y sqlite3 libinotify libiconv gettext-runtime pango cairo ca_root_nss zip automake autoconf bison gmake libtool perl5 python37
		;;
	13*)
		echo "Not ready yet."
		exit 1
		;;
esac
