#!/bin/sh
## Test the specified port

echo "Entering port_test"
if [ -z $PORT ]; then
	PORT=lang/mono
else
	PORT=$PORT
fi
echo "Building $PORT"

#cd /usr/ports
#echo "Performing make describe test."
#make describe
#cd $1
make -C $PORT distclean
make -C $PORT clean
echo "Checking stage..."
make -C $PORT stage
echo "Checking plist..."
make -C $PORT check-plist
echo "Checking stage-qa..."
make -C $PORT stage-qa
echo "Making package..."
make -C $PORT package
