#!/bin/sh
## Test the specified port

if [ -z $1 ]; then
	echo "Port name to test not provided."
	exit 1
fi

#cd /usr/ports
#echo "Performing make describe test."
#make describe
#cd $1
make -C /usr/ports/$1 distclean
make -C /usr/ports/$1 clean
echo "Checking stage..."
make -C /usr/ports/$1 stage
echo "Checking plist..."
make -C /usr/ports/$1 check-plist
echo "Checking stage-qa..."
make -C /usr/ports/$1 stage-qa
echo "Making package..."
make -C /usr/ports/$1 package
