#!/bin/sh
## Pull ports via svn instead of portsnap
#if [ -d /usr/ports ]; then
#	echo "Removing existing ports tree."
#	rm -rf /usr/ports
#fi
#echo "Checking out ports from svn..."
#svnlite update https://svn.freebsd.org/ports/head /usr/ports > /dev/null
#svnlite update /usr/ports 
#if [ $? -ne 0 ]; then
#	echo "Failed to check out ports from SVN."
#	exit 1
#fi
## XXX: it's portsnap, sigh.
env PAGER=cat portsnap fetch --interactive
portsnap extract > /dev/null
if [ $? -eq 0 ]; then
	echo "portsnap extracted successfully."
else
	RC=$?
	echo "portsnap failed"
	exit $RC
fi
#cp -r ${CIRRUS_WORKING_DIR}/lang/* /usr/ports/lang/
#cp -r ${CIRRUS_WORKING_DIR}/x11-toolkits/* /usr/ports/x11-toolkits/

## Setup system make.conf
if [ -f /etc/make.conf ]; then
	mv /etc/make.conf /etc/make.conf.bak
fi
cat << EOF > /etc/make.conf
DEFAULT_VERSIONS+=perl5=5.30
DEFAULT_VERSIONS+=ruby=2.6
DEFAULT_VERSIONS+=python2=2.7
DEFAULT_VERSIONS+=python3=3.7
OPTIONS_UNSET+=LANG_AF LANG_AK LANG_AM LANG_AR LANG_AST LANG_BB LANG_BE
OPTIONS_UNSET+=LANG_BG LANG_BN LANG_BR LANG_BS LANG_CA LANG_CS
OPTIONS_UNSET+=LANG_CY LANG_DA LANG_DE LANG_EL LANG_EO LANG_ES LANG_ET
OPTIONS_UNSET+=LANG_EU LANG_FA LANG_FI LANG_FR LANG_FY LANG_GA LANG_GB
OPTIONS_UNSET+=LANG_GD LANG_GL LANG_GU LANG_HE LANG_HI LANG_HR LANG_HU
OPTIONS_UNSET+=LANG_ID LANG_IS LANG_IT LANG_JA LANG_JP LANG_KK LANG_KN
OPTIONS_UNSET+=LANG_KO LANG_KU LANG_LG LANG_LK LANG_LT LANG_LV LANG_MAI
OPTIONS_UNSET+=LANG_MK LANG_ML LANG_MN LANG_MR LANG_NB LANG_NL LANG_NN
OPTIONS_UNSET+=LANG_NSO LANG_OR LANG_PA LANG_PBR LANG_PL LANG_PT LANG_RM
OPTIONS_UNSET+=LANG_RO LANG_RU LANG_SA LANG_SC LANG_SE LANG_SI LANG_SK
OPTIONS_UNSET+=LANG_SL LANG_SM LANG_SON LANG_SQ LANG_SR LANG_SV LANG_TA
OPTIONS_UNSET+=LANG_TE LANG_TH LANG_TR LANG_UA LANG_UK LANG_VI LANG_ZA
OPTIONS_UNSET+=LANG_ZU
EOF

