#!/bin/sh
## Test the specified port

if [ -z $1 ]; then
	echo "Port name to test not provided."
	exit 1
else
	echo "Building $1"
fi

#cd /usr/ports
#echo "Performing make describe test."
#make describe
#cd $1
make -C $1 distclean
make -C $1 clean
echo "Checking stage..."
make -C $1 stage
echo "Checking plist..."
make -C $1 check-plist
echo "Checking stage-qa..."
make -C $1 stage-qa
echo "Making package..."
make -C $1 package
